### ISSUE TITLE
berniesanders.com/#more not redirecting

### ISSUE THREAD

**Issue by feelthebern** [SandersForPresident/sandersforpresident.github.io#2]
On OSX Chrome 45.0.2454.99 (64-bit) (also tested in incognito mode) and Linux Firefox 39.0 clicking "More" does nothing. The "More" link works on OSX Firefox 35.0.1 and Linux Chromium 45.0.2454.85 Ubuntu 14.04 (64-bit).

This was working for me last week and I don't see any commits that could have changed this so I'm at a loss to explain or give suggestions.

**Comment by schneidmaster** [comment]
This is the repo for https://coders.forsanders.com - we don't run the official campaign site. I'll pass along your report to someone at the campaign though.
